### ISSUE TITLE
Not updating after v5

### ISSUE THREAD

**Issue by kevnk** [studio1902/statamic-peak-seo#34]
### Bug description

I've updated everything else I know how to update. But since v5.0, I haven't been able to update this add-on. Here are my add-ons and their versions:

```
CORE
Statamic				4.25.0	Up to date

ADDONS
Runway					5.3.3	Up to date
Statamic Peak Browser Appearance	3.2	Up to date
Statamic Peak Commands			2.6	Up to date
Statamic Peak SEO			5.0	6 updates
Statamic Peak Tools			3.2	Up to date
```

### How to reproduce

Not 100% sure... maybe install v5 and then try to run `composer update studio1902/statamic-peak-seo` ...

### Logs

```shell
After running `composer update studio1902/statamic-peak-seo` in terminal:


> Statamic\Console\Composer\Scripts::preUpdateCmd
Loading composer repositories with package information
Updating dependencies                                 
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   INFO  Discovering packages.  

  ajthinking/archetype ............................................................ DONE
  barryvdh/laravel-debugbar ....................................................... DONE
  doublethreedigital/runway ....................................................... DONE
  intervention/image .............................................................. DONE
  laravel/sail .................................................................... DONE
  laravel/sanctum ................................................................. DONE
  laravel/tinker .................................................................. DONE
  nesbot/carbon ................................................................... DONE
  nunomaduro/collision ............................................................ DONE
  nunomaduro/termwind ............................................................. DONE
  rebing/graphql-laravel .......................................................... DONE
  spatie/laravel-ignition ......................................................... DONE
  statamic/cms .................................................................... DONE
  studio1902/statamic-peak-browser-appearance ..................................... DONE
  studio1902/statamic-peak-commands ............................................... DONE
  studio1902/statamic-peak-seo .................................................... DONE
  studio1902/statamic-peak-tools .................................................. DONE
  wilderborn/partyline ............................................................ DONE

> @php artisan statamic:install --ansi
Discovered Addon: doublethreedigital/runway
Discovered Addon: studio1902/statamic-peak-browser-appearance
Discovered Addon: studio1902/statamic-peak-commands
Discovered Addon: studio1902/statamic-peak-seo
Discovered Addon: studio1902/statamic-peak-tools
Addon manifest generated successfully.

   INFO  Publishing [statamic] assets.  

  File [config/statamic/antlers.php] already exists ............................ SKIPPED  
  File [config/statamic/api.php] already exists ................................ SKIPPED  
  File [config/statamic/assets.php] already exists ............................. SKIPPED  
  File [config/statamic/autosave.php] already exists ........................... SKIPPED  
  File [config/statamic/cp.php] already exists ................................. SKIPPED  
  File [config/statamic/editions.php] already exists ........................... SKIPPED  
  File [config/statamic/forms.php] already exists .............................. SKIPPED  
  File [config/statamic/git.php] already exists ................................ SKIPPED  
  File [config/statamic/graphql.php] already exists ............................ SKIPPED  
  File [config/statamic/live_preview.php] already exists ....................... SKIPPED  
  File [config/statamic/markdown.php] already exists ........................... SKIPPED  
  File [config/statamic/oauth.php] already exists .............................. SKIPPED  
  File [config/statamic/protect.php] already exists ............................ SKIPPED  
  File [config/statamic/revisions.php] already exists .......................... SKIPPED  
  File [config/statamic/routes.php] already exists ............................. SKIPPED  
  File [config/statamic/search.php] already exists ............................. SKIPPED  
  File [config/statamic/static_caching.php] already exists ..................... SKIPPED  
  File [config/statamic/sites.php] already exists .............................. SKIPPED  
  File [config/statamic/stache.php] already exists ............................. SKIPPED  
  File [config/statamic/system.php] already exists ............................. SKIPPED  
  File [config/statamic/users.php] already exists .............................. SKIPPED  
  Copying directory [vendor/statamic/cms/resources/users] to [resources/users] .... DONE
  File [please] already exists ................................................. SKIPPED  

   INFO  Publishing [statamic-cp] assets.  

  Copying directory [vendor/statamic/cms/resources/dist] to [public/vendor/statamic/cp]  DONE

   INFO  Publishing [statamic-frontend] assets.  

  Copying directory [vendor/statamic/cms/resources/dist-frontend] to [public/vendor/statamic/frontend]  DONE

   INFO  Publishing [runway] assets.  

  Copying directory [vendor/doublethreedigital/runway/dist/build] to [public/vendor/runway/build]  DONE

   INFO  Compiled views cleared successfully.  

   INFO  Application cache cleared successfully.  

121 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan vendor:publish --tag=laravel-assets --ansi --force

   INFO  No publishable resources for tag [laravel-assets].  

Found 1 security vulnerability advisory affecting 1 package.
Run composer audit for a full list of advisories.
```

### Environment

```yaml
Environment
Application Name: My Site
Laravel Version: 10.17.1
PHP Version: 8.2.10
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: my-site.valet
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: mailgun
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.25.0 PRO

Statamic Addons
doublethreedigital/runway: 5.3.3
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.6
studio1902/statamic-peak-seo: 5.0
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
