### ISSUE TITLE
current_full_url shoul be current_url in hreflang generation check

### ISSUE THREAD

**Issue by K3CK** [studio1902/statamic-peak-seo#56]
### Bug description

Calling pages with GET parameters leads to multiple different entries in the (half) cache, as the returned HTML differs depending on if there are GET params present or not.

It seems that this is caused by the hreflang generation in the _seo.antlers.html snippet:
https://github.com/studio1902/statamic-peak-seo/blob/fd014b5e2478d41195cd28c1552f58e91b4ce650/resources/views/snippets/_seo.antlers.html#L54

The check `current_full_url === permalink` is wrong in my opinion. `current_full_url` returns the URL with GET params included, `permalink` does not include get params.

Therefore the hreflang tags do get generated in the HTML output if there are no GET params, but do not get generated if there are GET params present, what then again causes different cache entries.

Using `current_url` instead of `current_full_url` should do the trick, as the check works no matter if GET params are present or not.

### How to reproduce

Open any page of a project with and without GET params and compare the HTML code generated for the hreflang tags.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: xxx
Laravel Version: 10.48.28
PHP Version: 8.1.31
Composer Version: 2.4.4
Environment: production
Debug Mode: OFF
URL: xxx
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 2 (english, german)
Stache Watcher: Disabled
Static Caching: half
Version: 5.47.0 PRO

Statamic Addons
goldnead/statamic-toc: 1.6
mitydigital/feedamic: 2.5.0
statamic-rad-pack/meilisearch: 3.3.0
```

### Installation

Other (please explain)

### Antlers Parser

runtime (new)
