### ISSUE TITLE
Error: "The given selector #og did not match any elements" when generating social image

### ISSUE THREAD

**Issue by buddy94** [studio1902/statamic-peak-seo#58]
### Bug description

I suddenly started getting this error when trying to run the job to generate a social image:
`The given selector "#og" did not match any elements
`

### How to reproduce

Trigger the job that generates the social image

The error appears: The given selector #og did not match any elements

### Logs

```shell
Spatie\Browsershot\Exceptions\ElementNotFound: The given selector `#og did not match any elements in /home/forge/catt.ch/vendor/spatie/browsershot/src/Exceptions/ElementNotFound.php:11
Stack trace:
#0 /home/forge/catt.ch/vendor/spatie/browsershot/src/Browsershot.php(1112): Spatie\Browsershot\Exceptions\ElementNotFound::make()
#1 /home/forge/catt.ch/vendor/spatie/browsershot/src/Browsershot.php(646): Spatie\Browsershot\Browsershot->callBrowser()
#2 /home/forge/catt.ch/vendor/studio1902/statamic-peak-seo/src/Jobs/GenerateSocialImagesJob.php(75): Spatie\Browsershot\Browsershot->save()
#3 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Studio1902\PeakSeo\Jobs\GenerateSocialImagesJob->handle()
#4 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure()
#6 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#7 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Container/Container.php(696): Illuminate\Container\BoundMethod::call()
#8 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(126): Illuminate\Container\Container->call()
#9 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(170): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#10 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(127): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(130): Illuminate\Pipeline\Pipeline->then()
#12 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(126): Illuminate\Bus\Dispatcher->dispatchNow()
#13 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(170): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#14 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(127): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#15 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(121): Illuminate\Pipeline\Pipeline->then()
#16 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(69): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#17 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\Queue\CallQueuedHandler->call()
#18 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(442): Illuminate\Queue\Jobs\Job->fire()
#19 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(392): Illuminate\Queue\Worker->process()
#20 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(178): Illuminate\Queue\Worker->runJob()
#21 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(149): Illuminate\Queue\Worker->daemon()
#22 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(132): Illuminate\Queue\Console\WorkCommand->runWorker()
#23 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#24 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#25 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure()
#26 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#27 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Container/Container.php(696): Illuminate\Container\BoundMethod::call()
#28 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\Container\Container->call()
#29 /home/forge/catt.ch/vendor/symfony/console/Command/Command.php(279): Illuminate\Console\Command->execute()
#30 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\Component\Console\Command\Command->run()
#31 /home/forge/catt.ch/vendor/symfony/console/Application.php(1094): Illuminate\Console\Command->run()
#32 /home/forge/catt.ch/vendor/symfony/console/Application.php(342): Symfony\Component\Console\Application->doRunCommand()
#33 /home/forge/catt.ch/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRun()
#34 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(198): Symfony\Component\Console\Application->run()
#35 /home/forge/catt.ch/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1235): Illuminate\Foundation\Console\Kernel->handle()
#36 /home/forge/catt.ch/artisan(13): Illuminate\Foundation\Application->handleCommand()
#37 {main}
```

### Environment

```yaml
Environment
Application Name: CATT
Laravel Version: 11.44.2
PHP Version: 8.3.14
Composer Version: 2.8.8
Environment: production
Debug Mode: ENABLED
URL: catt.ch
Maintenance Mode: OFF
Timezone: Europe/Rome
Locale: it

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 8
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.52.0 PRO

Statamic Addons
ancom/admin-toolbar: dev-main
ancom/manage-newsletter: dev-main
statamic/eloquent-driver: 4.21.0
statamic/importer: 1.8.1
studio1902/statamic-peak-browser-appearance: 3.6.1
studio1902/statamic-peak-commands: 8.16.1
studio1902/statamic-peak-seo: 8.21.1
studio1902/statamic-peak-tools: 6.7.1

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: eloquent
Terms: eloquent
Tokens: file
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None

### Additional details
Here are a few things I already tried to solve the issue, but without success:

Reverted _social_image.antlers.html and social_image.antlers.html to their original state

Downgraded the related packages

Cleared caches and tried again

Unfortunately, the error still occurs every time I run the job.

Thanks in advance for your help!
